spring:
  application:
    name: companies
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/companies
    username: companies
    password: companies

flyway:
  table: schema_version
